# Generated by Django 4.2.6 on 2023-10-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="costumer", new_name="customer",
        ),
        migrations.RenameField(
            model_name="shippingaddress", old_name="costumer", new_name="customer",
        ),
    ]
